version: "3.7"

services:

  bosco-yolo-client:
    image: boscokipkosgei/bosco-yolo-client:v1.0.0
    container_name: bosco-yolo-client
    ports:
      - "3000:3000"
    depends_on:
      - bosco-yolo-backend
    networks:
      - app-net

  bosco-yolo-backend:
    image: boscokipkosgei/bosco-yolo-backend:v1.0.0
    container_name: bosco-yolo-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://app-mongo:27017/ecommerce
    depends_on:
      - app-mongo
    networks:
      - app-net

  app-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
    networks:
      - app-net

networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          # ip_range: 172.20.0.0/16

volumes:
  app-mongo-data:
    driver: local
