- name: Provision Servers 
  hosts: all
  become: yes    #All commands being executed as sudo
  tasks: 
    - name: Ensure NTP (chrony) is installed
      apt:
        name: chrony
        state: present
        update_cache: yes

    - name: Ensure chrony is running and enabled
      service:
        name: chrony
        state: started
        enabled: yes
    - name: Test Connectivity
      ping:  
    - name: Update Server
      apt:
        update_cache: yes 
