apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
      - name: yolo-backend
        image: docker.io/boscokipkosgei/bosco-yolo-backend:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo:27017"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"