apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: docker.io/boscokipkosgei/bosco-yolo-client:v1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://yolo-backend:5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"