apiVersion: v1
kind: Service
metadata:
  name: bosco-client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # Exposes the service externally with a cloud provider's load balancer